import ServiceClock from '../components/ServiceClock';
import useSimulation from '../services/useSimulation';
import {apiService} from '../services/api';
import {officerSession,officerCases} from '../services/officerAccounts';
import React,{useEffect,useState} from 'react';
import {useSearchParams,Link} from 'react-router-dom';
import {ArrowUpRight,CheckCircle2,Clock,MapPin} from 'lucide-react';
import {stages} from '../services/activityFeed';
const time=value=>new Date(value).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit',second:'2-digit'});
const labels={all:'All service requests',high:'High priority requests',pending:'Awaiting resolution',resolved:'Resolved & closed requests'};
export default function ActivityBoard({timeline=false}){
 const [params,setParams]=useSearchParams(),[feed]=useSimulation(),[saved,setSaved]=useState([]),[now,setNow]=useState(Date.now);
 const filter=Object.hasOwn(labels,params.get('filter'))?params.get('filter'):'all';
 useEffect(()=>{const clock=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(clock);},[]);
 useEffect(()=>{if(!timeline)return;let live=true;async function refresh(){try{const rows=officerSession()?officerCases():(await apiService.getComplaints({limit:1000})).complaints;if(live)setSaved(rows||[]);}catch{if(live)setSaved([]);}}refresh();const timer=setInterval(refresh,5000);return()=>{live=false;clearInterval(timer);};},[timeline]);
 const rows=feed.rows,shown=rows.filter(r=>filter==='all'||filter==='high'&&r.priority==='High'||filter==='pending'&&r.stage<3||filter==='resolved'&&r.stage>=3);
 
 const personal=saved.slice().sort((a,b)=>new Date(b.timestamp)-new Date(a.timestamp)).map(r=>({id:r.grievance_id,title:r.complaint_text.match(/TITLE:\s*(.*?)(?:\n|LOCATION:)/)?.[1]?.trim()||r.complaint_text.slice(0,100),location:r.department,stage:Math.max(0,['SUBMITTED','ASSIGNED','IN_PROGRESS','RESOLVED','CLOSED'].indexOf(r.status)),personal:true,history:(r.history||[{new_status:'SUBMITTED',changed_at:r.timestamp}]).map(h=>({stage:['SUBMITTED','ASSIGNED','IN_PROGRESS','RESOLVED','CLOSED'].indexOf(h.new_status),at:h.changed_at,remark:h.remark}))}));
 const options=[...personal,...rows.slice().sort((a,b)=>b.created-a.created)];
 const active=options.find(r=>r.id===params.get('id'))||options[0];
 const age=value=>{const seconds=Math.max(0,Math.floor((now-value)/1000));return seconds<60?seconds+'s ago':Math.floor(seconds/60)+'m ago';};
 return <div className="cf-home zero-activity"><div className="zero-service-masthead"><div><span className="zero-india-stripe"/>INDIA · CITIZEN SERVICES</div><ServiceClock large={!timeline}/></div><div className="cf-page-heading"><div><div className="cf-eyebrow">{timeline?'CASE HISTORY':'PUBLIC SERVICE MONITOR'}</div><h1>{timeline?'Case timeline':'Every concern. Visible progress.'}</h1><p>{timeline?'Follow the response history of a service request.':'Browse service requests by priority and resolution status.'}</p></div></div>
 {!timeline&&<><div className="zero-metrics">{[['all','Requests received',feed.sequence],['high','High priority',rows.filter(r=>r.priority==='High').length],['pending','Awaiting resolution',rows.filter(r=>r.stage<3).length],['resolved','Resolved / closed',rows.filter(r=>r.stage>=3).length]].map(([key,label,value])=><button key={key} aria-pressed={filter===key} className={filter===key?'active':''} onClick={()=>setParams({filter:key})}><span>{label}</span><strong key={value}>{value}</strong><ArrowUpRight size={16}/></button>)}</div><section className="cf-panel zero-wide-feed"><div className="cf-panel-heading"><h2>{labels[filter]}</h2><span className="cf-eyebrow">{shown.length} CASES</span></div><div className="zero-case-list">{shown.map(r=><Link key={r.id} to={'/timeline?id='+r.id} className={'zero-service-row stage-'+r.stage}><div className="zero-status-dot"/><div className="zero-case-copy"><small>{r.id} · {r.department}</small><h3>{r.title}</h3><div className="zero-case-location"><MapPin size={12}/>{r.location}</div></div><div className="zero-case-meta"><span className={'zero-state stage-'+r.stage}>{stages[r.stage]}</span><span className={'zero-priority '+r.priority.toLowerCase()}>{r.priority} priority</span><time title={new Date(r.updated).toLocaleString()}>{age(r.updated)}</time><small>{time(r.updated)}</small></div><ArrowUpRight size={16}/></Link>)}{!shown.length&&<p className="cf-empty">No matching cases right now. New requests appear automatically.</p>}</div></section></>}
 {timeline&&<section className="cf-panel zero-timeline zero-timeline-page"><label htmlFor="timeline-case">Choose a service request</label><select id="timeline-case" value={active.id} onChange={e=>setParams({id:e.target.value})}>{options.map(r=><option key={r.id} value={r.id}>{r.personal?'YOUR REQUEST · ':'SIMULATION · '}{r.id} · {r.title}</option>)}</select><div className="zero-case-progress" role="progressbar" aria-label="Case workflow progress" aria-valuemin={0} aria-valuemax={4} aria-valuenow={active.stage} aria-valuetext={stages[active.stage]}><span style={{width:((active.stage+1)/5*100)+'%'}}/></div><p>{active.stage+1} of 5 stages · {active.personal?'Your saved grievance':'Simulated service request'}</p><h2>{active.title}</h2><p>{active.id} · {active.location}</p><span className={'zero-state stage-'+active.stage}>{stages[active.stage]}</span><ol>{stages.map((step,i)=>{const event=active.history.filter(h=>h.stage===i).at(-1);return <li key={step} className={event?'complete':''}><span>{event?<CheckCircle2 size={18}/>:<Clock size={18}/>}</span><div><strong>{step}</strong><p>{event?new Date(event.at).toLocaleString('en-IN'):'Awaiting department action'}</p>{event?.remark&&<p>{event.remark}</p>}</div></li>})}</ol><Link className="cf-text-link" to="/activity">← Back to service activity</Link><Link className="cf-text-link" to="/history">Track your saved grievance →</Link></section>}
 <div className="zero-live-event zero-feed-bottom"><span className="zero-live-dot"/><div><strong>{feed.lastEvent}</strong><small>Live simulation · random updates every 3–7 seconds</small></div></div><p className="zero-simulation-note">Illustrative activity, not live government records. Your submitted grievances are separate. The latest 40 sample cases remain visible.</p></div>;
}
