import React, { useState } from 'react';
import { useNavigate, useLocation, Link } from 'react-router-dom';
import { ArrowRight, ArrowUpRight, LockKeyhole, Eye, EyeOff, AlertCircle, LoaderCircle, Check, Monitor, Server } from 'lucide-react';
import { apiService } from '../services/api';
export default function Login(){
 const navigate=useNavigate(),location=useLocation();
 const [username,setUsername]=useState(''),[password,setPassword]=useState(''),[visible,setVisible]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[mode,setMode]=useState('local');
 const enterGuest=()=>{sessionStorage.removeItem('project_profile');localStorage.removeItem('admin_token');localStorage.removeItem('admin_user');sessionStorage.setItem('project_guest','true');sessionStorage.setItem('project_mode',mode);const target=location.state?.from;navigate(target && /^\/(submit|history)(\?|$)/.test(target)?target:'/submit',{replace:true});};
 const submit=async e=>{e.preventDefault();setError('');setLoading(true);try{const r=await apiService.login(username.trim(),password);if(r.status!=='success'||!r.token)throw new Error(r.message||'Please check your credentials.');localStorage.setItem('admin_token',r.token);localStorage.setItem('admin_user',JSON.stringify(r.user));sessionStorage.removeItem('project_guest');sessionStorage.setItem('project_mode','connected');navigate('/admin/dashboard?tab=complaints',{replace:true});}catch(err){setError(err.message||'Unable to sign in. Please try again.');}finally{setLoading(false);}};
 return <div className="project-entry"><section className="project-entry-story"><img className="zero-login-photo" src="/india-gate.jpg" alt="India Gate illuminated at dusk in New Delhi"/><Link to="/login" className="project-wordmark"><img src="/india-emblem.svg" className="zero-india-emblem" alt="Emblem of India"/>PROJECT ZERO<span>PUBLIC SERVICES</span></Link><div className="project-story-content"><span className="project-overline">A CLEARER PATH TO RESOLUTION</span><h1>Better services.<br/><em>One concern<br/>at a time.</em></h1><p>A shared place to raise an issue, follow its progress, and keep every response in view.</p><div className="project-process">{['Describe the issue','Get a tracking reference','Follow every update'].map((x,i)=><div key={x}><span>0{i+1}</span>{x}<Check size={16}/></div>)}</div></div><div className="project-story-footer"><span>Independent civic demonstration.</span><span>Designed for accountability.</span></div></section>
 <section className="project-entry-access"><div className="project-access-heading"><span className="project-overline">YOUR PUBLIC SERVICE WORKSPACE</span><h2>Welcome to PROJECT ZERO</h2><p>Choose how you’d like to continue.</p></div>
 <div className="project-guest-card"><div className="project-card-title"><span className="project-icon-box"><ArrowUpRight size={22}/></span><div><h3>Here to report an issue?</h3><p>No account or password needed.</p></div></div><fieldset className="project-mode"><legend>Workspace</legend><label><input type="radio" name="mode" checked={mode==='local'} onChange={()=>setMode('local')}/><Monitor size={16}/>Local workspace</label><label><input type="radio" name="mode" checked={mode==='connected'} onChange={()=>setMode('connected')}/><Server size={16}/>Connected API</label></fieldset><p className="project-mode-help">{mode==='local'?'Try the full citizen flow. Records stay in this browser; category suggestions use a trained local NLP model.':'Send and track grievances through your running Flask service.'}</p><button className="project-primary" onClick={enterGuest} disabled={loading}>Continue as guest<ArrowRight size={18}/></button></div>
 <div className="zero-account-links"><span>Want to save your details?</span><Link to="/account">Create account / Citizen sign in <ArrowUpRight size={14}/></Link></div><div className="project-divider"><span>FOR DEPARTMENT OFFICERS</span></div><form className="project-login-form" onSubmit={submit}><div className="project-form-title"><LockKeyhole size={17}/><h3>Officer sign in</h3></div>{error&&<div role="alert" className="project-error"><AlertCircle size={17}/>{error}</div>}<label htmlFor="officer-username">Username</label><input id="officer-username" autoComplete="username" required value={username} onChange={e=>setUsername(e.target.value)} placeholder="Enter your username" disabled={loading}/><label htmlFor="officer-password">Password</label><div className="project-password"><input id="officer-password" autoComplete="current-password" required type={visible?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter your password" disabled={loading}/><button type="button" onClick={()=>setVisible(!visible)} aria-label={visible?'Hide password':'Show password'} aria-pressed={visible}>{visible?<EyeOff size={18}/>:<Eye size={18}/>}</button></div><button className="project-officer-submit" disabled={loading}>{loading?<><LoaderCircle className="animate-spin" size={17}/>Signing in…</>:<>Sign in to officer workspace<ArrowRight size={17}/></>}</button><p className="project-signin-note">Officer access requires your local API to be running.</p></form><footer className="project-entry-footer">PROJECT ZERO · Public grievance management<span>Local first. Clear by design.</span></footer></section></div>;
}
